name: main

on: push

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/padm2pdfgen:${{ github.sha }}

jobs:
  build:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          echo ${IMAGE}
  deploy-dev:
    if: github.ref == 'refs/heads/master'
    name: Deploy to NAIS Dev-fss
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator.yaml

  deploy-dev-gcp:
    if: github.ref == 'refs/heads/master'
    name: Deploy to NAIS Dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/naiserator-dev-gcp.yaml

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    name: Deploy to NAIS Prod-fss
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/naiserator.yaml

  deploy-prod-gcp:
    if: github.ref == 'refs/heads/master'
    name: Deploy to NAIS Prod-gcp
    needs: deploy-dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/naiserator-prod-gcp.yaml
